### ISSUE TITLE
PHP 파일 끝 닫는 태그 제거 및 들여쓰기 수정

### ISSUE THREAD

**Issue by YJSoft** [daolcms/daol-core#100]
한줄 if문 등 들여쓰기가 제대로 되어있지 않아 개발에 불편함
또한 불필요한 `?>`는 추후 오류의 원인이 될수있음

**Comment by dorami** [comment]
모든 `?>` 태그를 삭제해야하나요?

**Comment by YJSoft** [comment]
@dorami 네. PHP 코드 이후 HTML을 작성할게 아니라면야 불필요하며, 닫는 태그 이후에 문자열이 올 경우 오류의 원인이 됩니다.

**Comment by dorami** [comment]
@YJSoft 봇하나 만들어서 일괄처리 하겠습니다.

**Comment by dorami** [comment]
@YJSoft 봇으로 할려고 하니 좀 오류가 발생하네요. 수작업으로 진행하겠습니다.

**Comment by YJSoft** [comment]
php 파일 들여쓰기 일괄수정 완료
