### ISSUE TITLE
새 MINIFY 스크립트 적용 및 테스트

### ISSUE THREAD

**Issue by YJSoft** [daolcms/daol-core#114]
XE 코어의 것을 가져왔으나 minify 누락된 파일이 있거나, minify 이후 동작이 달라지는 문제 등이 있을수 있으므로 충분한 테스트가 필요합니다.

**Comment by dorami** [comment]
자동으로 MINIFY 되나요?

**Comment by YJSoft** [comment]
@dorami 자동은 아니고 배포시 수동으로 gruntjs 실행으로 minify해줘야 합니다.
배포 스크립트까지 가져오면 배포시점에서 자동으로 minify하게 할수 있긴 합니다.

**Comment by dorami** [comment]
@YJSoft 그렇다면.. 배포시 마다 어떻게 해야하나요?

**Comment by dorami** [comment]
@YJSoft MINIFY 자동으로 하려는데 잘 안되네요.. 혹시 좀 도와주실 수 있으신가요?
그리고 수동으로 하게되면 어떻게 해야하나요??

**Comment by dorami** [comment]
@YJSoft Grunt문제는 해결했습니다.
js파일이 많이 변경되었던데, XE 에서 수정 없이 가져온 건가요?

**Comment by YJSoft** [comment]
@dorami XE에서 가져오면서 일부 다른부분(기본스킨 폴더명)이나 없는 파일만 바꿨습니다

**Comment by dorami** [comment]
테스트 결과 큰 이상없음. 추가로 버그 발견시 다음 버전에 패치 예정.
