### ISSUE TITLE
Object 클래스의 이름 충돌로 인한 클래스 이름 변경

### ISSUE THREAD

**Issue by YJSoft** [daolcms/daol-core#128]
xpressengine/xe-core#2181 참고
`Object` 클래스명이 `BaseObject` 클래스로 변경되어야 하며 기존 Object 클래스는 `class_alias` 함수로 유지

**Comment by dorami** [comment]
https://github.com/daolcms/daol-core/commit/66ed24a1766439df2618ee558ddc7cfd628c7b2b 적용
