### ISSUE TITLE
게시판에서 이미지 클릭하면 뜨는 이미지가 너무 높게 뜹니다.

### ISSUE THREAD

**Issue by pentopen** [daolcms/daol-core#78]
게시판에서 이미지를 클릭하면 원래 사이즈로 화면에 뜨는데 다올 1.0.1.9에서 이미지가 화면에 너무 높이 뜨는것 같습니다.
그리고 원본 이미지가 화면에 떴을때 xe 공홈처럼 이미지를 마우스로 움직일수 있었으면 합니다.
고려 바람니다.

수고하세요.

**Comment by dorami** [comment]
게시판 모듈 교체 후 확인해 보겠습니다.

**Comment by dorami** [comment]
@pentopen XE 1.8.20과 배포 예정인 다올 CMS 1.0.2.1에서 동일 결과가 나옵니다.
테스트 환경은 레이아웃을 사용하지 않았습니다.

**Comment by pentopen** [comment]
제가 사용하는 레이아웃은 https://www.xpressengine.com/index.php?mid=download&package_id=19506416 이것을 살짝 수정해서 사용하고있습니다만..
레이아웃을 제거하니 저도 동일 결과가 나오는군요...
지금까지 XE 1.5.4.3만 사용해봐서 몰랐는데 레이아웃에 따라 이렇게 차이가 날줄은 몰랐네요.
다올의 문제가 아니라 제 레이아웃의 문제인것 같군요...

**Comment by dorami** [comment]
문제없어 이슈 닫습니다.
