### ISSUE TITLE
보안패치 이후 메뉴 제목에 태그사용 불가능

### ISSUE THREAD

**Issue by YJSoft** [daolcms/daol-core#92]
보안패치 이후 메뉴 제목에 태그사용 불가능하며 입력시 지워져버림. 메뉴는 관리자만 편집 가능하므로 태그를 제거할 필요 없으나 불필요하게 제거되어 발생되는 현상.

**Comment by dorami** [comment]
이 패치 적용에 고민 중입니다.. @YJSoft 님은 어떻게 생각하나요.

**Comment by YJSoft** [comment]
@dorami 하위 호환성을 위해서라도 메뉴명에 기본적인 태그는 사용허가해야 한다고 생각합니다. 당장 XE 업뎃한 이후 왜 안되냐는 글이 종종 보이네요(캐시파일 재생성 전까지는 메뉴 아이콘이 남아있어 많지는 않은것 같습니다)

**Comment by dorami** [comment]
@YJSoft XE 보안패치 반영과 이 패치를 반영하여 1.0.2.6 에서 배포할 예정입니다.

**Comment by YJSoft** [comment]
@dorami `release/1.0.2.6` 브랜치를 `master` 브랜치에 머지하시고 배포하시면 될겁니다

**Comment by dorami** [comment]
@YJSoft 확인했습니다. 감사합니다.
